name: quizbee-local-new

services:
  # APPS
  api:
    build:
      context: .
      dockerfile: ../apps/api/Dockerfile.local
    env_file:
      - ../envs/.env
    volumes:
      - ../:/repo
    ports:
      - "8000:8000"

  # worker:
  #   build:
  #     context: .
  #     dockerfile: apps/worker/Dockerfile.local
  #   env_file:
  #     - ../envs/.env
  #   volumes:
  #     - ../apps/worker/src:/app/src
  #   command: ["uv", "run", "python", "-m", "worker"]

  web:
    build:
      context: .
      dockerfile: ../apps/web/Dockerfile.local
    env_file:
      - ../envs/.env
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - ../:/repo
      - pnpm-store:/pnpm
      - /repo/apps/web/node_modules
    working_dir: /repo
    ports:
      - "4321:4321"

  app:
    build:
      context: .
      dockerfile: ../apps/app/Dockerfile.local
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=1
    env_file:
      - ../envs/.env
    volumes:
      - ../:/repo
      - pnpm-store:/pnpm
      - /repo/apps/app/node_modules
    working_dir: /repo
    ports:
      - "5173:5173"

  # INFRA
  pb:
    build:
      context: .
      dockerfile: ../apps/pb/Dockerfile.local
    env_file:
      - ../envs/.env
    volumes:
      - ../apps/pb/pb_data:/pb/pb_data
      - ../apps/pb/pb_migrations:/pb/pb_migrations:ro
      - ../apps/pb/pb_hooks:/pb/pb_hooks:ro
    ports:
      - "8090:8090"

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - ../apps/meilisearch/data:/meili_data
    env_file:
      - ../envs/.env

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ports:
      - "6379:6379"
    volumes:
      - ../apps/dragonfly/data:/data
    env_file:
      - ../envs/.env

volumes:
  pnpm-store:
