name: quizbee-local

services:
  pb:
    build:
      context: ../apps/pb
      dockerfile: Dockerfile
    env_file:
      - ../envs/.env
    volumes:
      - ../apps/pb/pb_data:/pb/pb_data
      - ../apps/pb/pb_migrations:/pb/pb_migrations
      - ../apps/pb/pb_hooks:/pb/pb_hooks
    ports:
      - "8090:8090"

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - ../apps/meilisearch/data:/meili_data
    env_file:
      - ../envs/.env

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ports:
      - "6379:6379"
    volumes:
      - ../apps/dragonfly/data:/data
    env_file:
      - ../envs/.env
