from typing import Protocol

from .models import Attempt, Quiz, QuizItem


class AttemptRepository(Protocol):
    async def get(self, id: str) -> Attempt: ...
    async def save(self, attempt: Attempt) -> None: ...


class QuizRepository(Protocol):
    async def get(self, id: str) -> Quiz: ...
    async def save_item(self, item: QuizItem) -> None: ...

    # async def get_user(self, user_id: str) -> list[Quiz]: ...
    async def save(self, quiz: Quiz) -> None: ...


class UOW(Protocol):
    quizzes: QuizRepository
    attempts: AttemptRepository

    def __enter__(self) -> "UOW": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class QuizIndexer(Protocol):
    async def index(self, quiz: Quiz) -> None: ...

    async def search(
        self, user_id: str, query: str, limit: int, ratio: float, threshold: float
    ) -> list[Quiz]: ...


class PatchGenerator(Protocol):
    async def generate(self, quiz: Quiz, cache_key: str) -> None: ...


class Finalizer(Protocol):
    async def finalize(self, quiz: Quiz) -> None: ...
