from typing import Protocol

from .models import Attempt, Quiz


class AttemptRepository(Protocol):
    async def get(self, id: str) -> Attempt: ...
    async def save(self, attempt: Attempt) -> None: ...


class QuizRepository(Protocol):
    async def get(self, id: str) -> Quiz: ...
    async def get_user_quizzes(self, user_id: str) -> list[Quiz]: ...
    async def save(self, quiz: Quiz) -> None: ...


class UOW(Protocol):
    quizzes: QuizRepository
    attempts: AttemptRepository

    def __enter__(self) -> "UOW": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class QuizIndexer(Protocol):
    async def index(self, quiz: Quiz) -> None: ...

    async def search(self, user_id: str, query: str, limit: int) -> list[Quiz]: ...
