name: meili-prod-with-backup

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: ${MEILI_NO_ANALYTICS:-true}
      MEILI_ENV: ${MEILI_ENV:-production}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_DB_PATH: /meili_data/data
      MEILI_DUMPS_DIR: /meili_data/dumps
      MEILI_SNAPSHOTS_DIR: /meili_data/snapshots
    volumes:
      - meili_data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:7700/health"]
      interval: 2s
      timeout: 10s
      retries: 15

  sidecar:
    build:
      context: .
      dockerfile: Dockerfile.sidecar
      args:
        MC_ARCH: ${MC_ARCH_OVERRIDE:-linux-amd64}
    depends_on:
      meilisearch:
        condition: service_started
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT} # напр. https://s3.eu-central-1.amazonaws.com или https://s3.example.com
      S3_REGION: ${S3_REGION} # напр. eu-central-1
      S3_BUCKET: ${S3_BUCKET} # напр. my-meili-backups
      # Опционально: префикс для PR/окружений
      BACKUP_PREFIX: ${BACKUP_PREFIX:-prod}
    volumes:
      - meili_data:/meili_data
      - ./backup.sh:/backup.sh:ro

volumes:
  meili_data:
