from typing import Protocol

from src.lib.config import LLMS


class LLMToolsApp(Protocol):
    @property
    def chunk_size(self) -> int: ...

    def encode(self, text: str, llm: LLMS = LLMS.GPT_5_MINI) -> list[int]: ...
    def decode(self, tokens: list[int], llm: LLMS = LLMS.GPT_5_MINI) -> str: ...
    def count_text(self, text: str, llm: LLMS = LLMS.GPT_5_MINI) -> int: ...
    def count_image(self, width: int, height: int) -> int: ...
    def chunk(self, text: str, respect_pages: bool = False) -> list[str] | list: ...
