from typing import Protocol
import numpy as np

from src.lib.config import LLMS

from ..domain.out import Vectorizer, RerankResult, ChunkWithPages


class LLMToolsApp(Protocol):
    @property
    def chunk_size(self) -> int: ...

    @property
    def vectorizer(self) -> Vectorizer: ...

    def encode(self, text: str, llm: LLMS = LLMS.GPT_5_MINI) -> list[int]: ...
    def decode(self, tokens: list[int], llm: LLMS = LLMS.GPT_5_MINI) -> str: ...
    def count_text(self, text: str, llm: LLMS = LLMS.GPT_5_MINI) -> int: ...
    def count_image(self, width: int, height: int) -> int: ...
    def chunk(self, text: str) -> list[str]: ...
    def chunk_with_pages(self, text: str) -> list[ChunkWithPages]: ...

    async def vectorize(self, chunks: list[str]) -> np.ndarray: ...
    async def rerank(
        self,
        user_id: str,
        session_id: str,
        query: str,
        documents: list[str],
        top_k: int = 4,
    ) -> list[RerankResult]: ...
