FROM python:3.13-slim
WORKDIR /repo

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    UV_LINK_MODE=symlink

RUN pip install -U uv watchfiles

# создаём env прямо в каталоге проекта
CMD ["sh", "-lc", "\
  uv sync -p apps/api --dev && \
  uv run -p apps/api uvicorn src.bootstrap:app --host 0.0.0.0 --port 8000 --reload \
"]
